#==========================================#
#    Welcome to OMEN44's Economy plugin    #
#                                          #
# This plugin adds basic economy commands  #
#        such as /balance and /pay         #
#                                          #
# Players gain money from mining different #
# blocks found in the world here is where  #
# you can configure what blocks they need  #
#   to mine and how much money they get    #
#==========================================#

# your list should look like this:
# blocks:
#   <block name>:
#     The amount of money dropped is a random one of the values you set here
#     - <amount of $>
#     - <amount of $>

money:
  moneySymbol: $ # the symbol that the plugin will use to present the money with
  deathLossPercent: 10 # when player's die, how much percent of their money do you want them to lose?
  defaultAmount: 200 # what amount do you want players to start with?

back:
  backAllowed: false
  backCost: 2000

# example for the Block Earning system
blocks:
  DIAMOND_ORE:
    - 100
  COAL_ORE:
    - 20
    - 5
    - 1

shop:
  shopPrice: 250 # this is the default cost per shop available
  shopLimit: 5 # this is how many shops a player can have, will be toggleable later on