name: IndroEconomy
version: 2.1.1
main: io.github.omen44.indroEconomy.IndroEconomy
api-version: 1.17
load: STARTUP
depend:
  - Vault
commands:
  back:
    description: "Allow player to return to their previous death point"
    usage: /back
    permission: indroEconomy.back