name: IndroEconomy
version: 2.0.1
main: io.github.omen44.indroEconomy.IndroEconomy
api-version: 1.17
depend:
  - Vault
permissions: {
               "indroEconomy.admin.setmoney",
               "indroEconomy.gamble"
}