name: IndroEconomy
version: 2.1.3
main: io.github.omen44.indroEconomy.IndroEconomy
api-version: 1.17
load: STARTUP
softdepend:
  - Vault
permissions: {"indroEconomy.stock", "indroEconomy.stock.insider", "indroEconomy.admin.setMoney", "indroEconomy.admin.reload"}